const POLARIS_DEFAULT_RA = '3:07:14.9';
const POLARIS_DEFAULT_DEC = '89:22:27.3';

const SIGMA_OCTANTIS_DEFAULT_RA = '21:29:46.0';
const SIGMA_OCTANTIS_DEFAULT_DEC = '-88:51:10.5';

export {
    POLARIS_DEFAULT_RA,
    POLARIS_DEFAULT_DEC,
    SIGMA_OCTANTIS_DEFAULT_RA,
    SIGMA_OCTANTIS_DEFAULT_DEC
};
